// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SignalScribe.Data;

#nullable disable

namespace SignalScribe.Migrations
{
    [DbContext(typeof(SignalScribeContext))]
    [Migration("20260816041317_TransmissionTranscribedByModel")]
    partial class TransmissionTranscribedByModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("SignalScribe.Data.Models.CaptureSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AgcEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CenterFrequencyHz")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChannelSpacingHz")
                        .HasColumnType("INTEGER");

                    b.Property<double>("DeviationHz")
                        .HasColumnType("REAL");

                    b.Property<string>("DeviceSerial")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("GainReductionDb")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LnaState")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MonitorHighHz")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MonitorLowHz")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SampleRateHz")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SquelchCloseDb")
                        .HasColumnType("REAL");

                    b.Property<int>("SquelchHangMs")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SquelchOpenDb")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("CaptureSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgcEnabled = true,
                            CenterFrequencyHz = 146000000L,
                            ChannelSpacingHz = 12500,
                            DeviationHz = 5000.0,
                            GainReductionDb = 40,
                            LnaState = 0,
                            MonitorHighHz = 148000000L,
                            MonitorLowHz = 144000000L,
                            SampleRateHz = 6400000L,
                            SquelchCloseDb = 5.0,
                            SquelchHangMs = 400,
                            SquelchOpenDb = 8.0
                        });
                });

            modelBuilder.Entity("SignalScribe.Data.Models.Channel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Callsign")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<double?>("CtcssToneHz")
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FrequencyHz")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("LearnedStateJson")
                        .HasColumnType("TEXT");

                    b.Property<double?>("NoiseFloorDbfs")
                        .HasColumnType("REAL");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FrequencyHz")
                        .IsUnique();

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("SignalScribe.Data.Models.DiscardedClip", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AudioPath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("FrequencyHz")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ModulationDepth")
                        .HasColumnType("REAL");

                    b.Property<double>("PeakDbfs")
                        .HasColumnType("REAL");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<double>("SpeechBandRatio")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SustainedTone")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SyllableRateHz")
                        .HasColumnType("REAL");

                    b.Property<int>("VoicedMs")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StartUtc");

                    b.ToTable("DiscardedClips");
                });

            modelBuilder.Entity("SignalScribe.Data.Models.Job", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LeaseUntilUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LeasedBy")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Status", "Type");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("SignalScribe.Data.Models.Marker", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<int>("OffsetMs")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TransmissionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TransmissionId", "OffsetMs");

                    b.ToTable("Markers");
                });

            modelBuilder.Entity("SignalScribe.Data.Models.Net", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DayOfWeekUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly?>("StartTimeUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.ToTable("Nets");
                });

            modelBuilder.Entity("SignalScribe.Data.Models.Segment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Callsign")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmbeddingModel")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("EndMs")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("SpeakerEmbedding")
                        .HasColumnType("BLOB");

                    b.Property<long?>("SpeakerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Transcript")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranscriptionModel")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("TransmissionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Callsign");

                    b.HasIndex("SpeakerId");

                    b.HasIndex("TransmissionId");

                    b.ToTable("Segments");
                });

            modelBuilder.Entity("SignalScribe.Data.Models.SegmentSearchHit", b =>
                {
                    b.Property<double>("Rank")
                        .HasColumnType("REAL");

                    b.Property<long>("SegmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Snippet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("SignalScribe.Data.Models.Session", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsNet")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("NetId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<string>("SummaryModel")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NetId");

                    b.HasIndex("ChannelId", "StartUtc");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("SignalScribe.Data.Models.Speaker", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Callsign")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("EmbeddingCentroid")
                        .HasColumnType("BLOB");

                    b.Property<string>("EmbeddingModel")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstHeardUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastHeardUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Callsign");

                    b.ToTable("Speakers");
                });

            modelBuilder.Entity("SignalScribe.Data.Models.Transmission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AudioPath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDouble")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("MeanCarrierOffsetHz")
                        .HasColumnType("REAL");

                    b.Property<double>("PeakDbfs")
                        .HasColumnType("REAL");

                    b.Property<long?>("SessionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranscribedByModel")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("VoicedMs")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("ChannelId", "StartUtc")
                        .IsUnique();

                    b.ToTable("Transmissions");
                });

            modelBuilder.Entity("SignalScribe.Data.Models.WorkerSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiscardRetentionHours")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxJobsPerClaim")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Paused")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SummaryModel")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("TranscriptionPrompt")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("WhisperModel")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WorkerSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DiscardRetentionHours = 24,
                            MaxJobsPerClaim = 4,
                            Paused = false,
                            SummaryModel = "Qwen2.5-7B-Instruct-Q4_K_M.gguf",
                            TranscriptionPrompt = "Amateur radio net. QSL, QRZ, seventy-three, net control, check-in, kerchunk, repeater, simplex, CQ, destinated.",
                            WhisperModel = "ggml-small.en-q5_1.bin"
                        });
                });

            modelBuilder.Entity("SignalScribe.Data.Models.Marker", b =>
                {
                    b.HasOne("SignalScribe.Data.Models.Transmission", "Transmission")
                        .WithMany("Markers")
                        .HasForeignKey("TransmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transmission");
                });

            modelBuilder.Entity("SignalScribe.Data.Models.Net", b =>
                {
                    b.HasOne("SignalScribe.Data.Models.Channel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("SignalScribe.Data.Models.Segment", b =>
                {
                    b.HasOne("SignalScribe.Data.Models.Speaker", "Speaker")
                        .WithMany("Segments")
                        .HasForeignKey("SpeakerId");

                    b.HasOne("SignalScribe.Data.Models.Transmission", "Transmission")
                        .WithMany("Segments")
                        .HasForeignKey("TransmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Speaker");

                    b.Navigation("Transmission");
                });

            modelBuilder.Entity("SignalScribe.Data.Models.Session", b =>
                {
                    b.HasOne("SignalScribe.Data.Models.Channel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SignalScribe.Data.Models.Net", "Net")
                        .WithMany("Sessions")
                        .HasForeignKey("NetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Channel");

                    b.Navigation("Net");
                });

            modelBuilder.Entity("SignalScribe.Data.Models.Transmission", b =>
                {
                    b.HasOne("SignalScribe.Data.Models.Channel", "Channel")
                        .WithMany("Transmissions")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SignalScribe.Data.Models.Session", "Session")
                        .WithMany("Transmissions")
                        .HasForeignKey("SessionId");

                    b.Navigation("Channel");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("SignalScribe.Data.Models.Channel", b =>
                {
                    b.Navigation("Transmissions");
                });

            modelBuilder.Entity("SignalScribe.Data.Models.Net", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("SignalScribe.Data.Models.Session", b =>
                {
                    b.Navigation("Transmissions");
                });

            modelBuilder.Entity("SignalScribe.Data.Models.Speaker", b =>
                {
                    b.Navigation("Segments");
                });

            modelBuilder.Entity("SignalScribe.Data.Models.Transmission", b =>
                {
                    b.Navigation("Markers");

                    b.Navigation("Segments");
                });
#pragma warning restore 612, 618
        }
    }
}
